"""Shared UI parameter specs for model/selector hyperparameters."""

from .forecasting import FORECASTING_MODEL_PARAM_SPECS
from .regression import (
    REGRESSION_MODEL_PARAM_SPECS,
    REGRESSION_SELECTOR_PARAM_SPECS,
    REGRESSION_REDUCER_PARAM_SPECS,
    REGRESSION_REDUCER_DEFAULTS,
)

__all__ = [
    "FORECASTING_MODEL_PARAM_SPECS",
    "REGRESSION_MODEL_PARAM_SPECS",
    "REGRESSION_SELECTOR_PARAM_SPECS",
    "REGRESSION_REDUCER_PARAM_SPECS",
    "REGRESSION_REDUCER_DEFAULTS",
]
