
from __future__ import annotations
REGRESSION_MODEL_PARAM_SPECS: dict[str, list[dict[str, object]]] = {
    "linear_regression": [
        {
            "name": "fit_intercept",
            "type": "bool",
            "label": "Fit intercept",
            "help_key": "controls.regression.hyperparams.models.linear_regression.fit_intercept",
        },
        {
            "name": "positive",
            "type": "bool",
            "label": "Positive coefficients",
            "help_key": "controls.regression.hyperparams.models.linear_regression.positive",
        },
    ],
    "ridge": [
        {
            "name": "alpha",
            "type": "float",
            "label": "Alpha (regularization)",
            "min": 0.0,
            "max": 1000.0,
            "step": 0.1,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.ridge.alpha",
        },
        {
            "name": "solver",
            "type": "choice",
            "label": "Solver",
            "choices": ["auto", "svd", "cholesky", "lsqr", "sparse_cg", "sag", "saga", "lbfgs"],
            "help_key": "controls.regression.hyperparams.models.ridge.solver",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.ridge.random_state",
        },
    ],
    "lasso": [
        {
            "name": "alpha",
            "type": "float",
            "label": "Alpha (regularization)",
            "min": 0.0,
            "max": 1000.0,
            "step": 0.1,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.lasso.alpha",
        },
        {
            "name": "max_iter",
            "type": "int",
            "label": "Max iterations",
            "min": 100,
            "max": 10000,
            "step": 100,
            "help_key": "controls.regression.hyperparams.models.lasso.max_iter",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.lasso.random_state",
        },
    ],
    "elastic_net": [
        {
            "name": "alpha",
            "type": "float",
            "label": "Alpha (regularization)",
            "min": 0.0,
            "max": 1000.0,
            "step": 0.1,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.elastic_net.alpha",
        },
        {
            "name": "l1_ratio",
            "type": "float",
            "label": "L1 ratio",
            "min": 0.0,
            "max": 1.0,
            "step": 0.1,
            "decimals": 2,
            "help_key": "controls.regression.hyperparams.models.elastic_net.l1_ratio",
        },
        {
            "name": "max_iter",
            "type": "int",
            "label": "Max iterations",
            "min": 100,
            "max": 10000,
            "step": 100,
            "help_key": "controls.regression.hyperparams.models.elastic_net.max_iter",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.elastic_net.random_state",
        },
    ],
    "polynomial_regression": [
        {
            "name": "degree",
            "type": "int",
            "label": "Polynomial degree",
            "min": 1,
            "max": 5,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.polynomial_regression.degree",
        },
        {
            "name": "fit_intercept",
            "type": "bool",
            "label": "Fit intercept",
            "help_key": "controls.regression.hyperparams.models.polynomial_regression.fit_intercept",
        },
    ],
    "random_forest": [
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of trees",
            "min": 10,
            "max": 2000,
            "step": 10,
            "help_key": "controls.regression.hyperparams.models.random_forest.n_estimators",
        },
        {
            "name": "max_depth",
            "type": "int_optional",
            "label": "Max depth",
            "min": 1,
            "max": 64,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.random_forest.max_depth",
        },
        {
            "name": "min_samples_split",
            "type": "int",
            "label": "Min samples split",
            "min": 2,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.random_forest.min_samples_split",
        },
        {
            "name": "min_samples_leaf",
            "type": "int",
            "label": "Min samples leaf",
            "min": 1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.random_forest.min_samples_leaf",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.random_forest.random_state",
        },
    ],
    "extra_trees": [
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of trees",
            "min": 10,
            "max": 2000,
            "step": 10,
            "help_key": "controls.regression.hyperparams.models.extra_trees.n_estimators",
        },
        {
            "name": "max_depth",
            "type": "int_optional",
            "label": "Max depth",
            "min": 1,
            "max": 64,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.extra_trees.max_depth",
        },
        {
            "name": "min_samples_split",
            "type": "int",
            "label": "Min samples split",
            "min": 2,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.extra_trees.min_samples_split",
        },
        {
            "name": "min_samples_leaf",
            "type": "int",
            "label": "Min samples leaf",
            "min": 1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.extra_trees.min_samples_leaf",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.extra_trees.random_state",
        },
    ],
    "gradient_boosting": [
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of boosting stages",
            "min": 10,
            "max": 2000,
            "step": 10,
            "help_key": "controls.regression.hyperparams.models.gradient_boosting.n_estimators",
        },
        {
            "name": "learning_rate",
            "type": "float",
            "label": "Learning rate",
            "min": 0.001,
            "max": 2.0,
            "step": 0.01,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.gradient_boosting.learning_rate",
        },
        {
            "name": "max_depth",
            "type": "int",
            "label": "Max depth",
            "min": 1,
            "max": 32,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.gradient_boosting.max_depth",
        },
        {
            "name": "min_samples_split",
            "type": "int",
            "label": "Min samples split",
            "min": 2,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.gradient_boosting.min_samples_split",
        },
        {
            "name": "min_samples_leaf",
            "type": "int",
            "label": "Min samples leaf",
            "min": 1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.gradient_boosting.min_samples_leaf",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.gradient_boosting.random_state",
        },
    ],
    "adaboost": [
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of estimators",
            "min": 10,
            "max": 500,
            "step": 10,
            "help_key": "controls.regression.hyperparams.models.adaboost.n_estimators",
        },
        {
            "name": "learning_rate",
            "type": "float",
            "label": "Learning rate",
            "min": 0.001,
            "max": 2.0,
            "step": 0.01,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.adaboost.learning_rate",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.adaboost.random_state",
        },
    ],
    "svr": [
        {
            "name": "kernel",
            "type": "choice",
            "label": "Kernel",
            "choices": ["rbf", "linear", "poly", "sigmoid"],
            "help_key": "controls.regression.hyperparams.models.svr.kernel",
        },
        {
            "name": "C",
            "type": "float",
            "label": "Regularization (C)",
            "min": 0.001,
            "max": 100.0,
            "step": 0.1,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.svr.c",
        },
        {
            "name": "epsilon",
            "type": "float",
            "label": "Epsilon",
            "min": 0.0,
            "max": 1.0,
            "step": 0.01,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.models.svr.epsilon",
        },
    ],
    "knn": [
        {
            "name": "n_neighbors",
            "type": "int",
            "label": "Number of neighbors",
            "min": 1,
            "max": 100,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.knn.n_neighbors",
        },
        {
            "name": "weights",
            "type": "choice",
            "label": "Weights",
            "choices": ["uniform", "distance"],
            "help_key": "controls.regression.hyperparams.models.knn.weights",
        },
        {
            "name": "algorithm",
            "type": "choice",
            "label": "Algorithm",
            "choices": ["auto", "ball_tree", "kd_tree", "brute"],
            "help_key": "controls.regression.hyperparams.models.knn.algorithm",
        },
    ],
    "decision_tree": [
        {
            "name": "max_depth",
            "type": "int_optional",
            "label": "Max depth",
            "min": 1,
            "max": 64,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.decision_tree.max_depth",
        },
        {
            "name": "min_samples_split",
            "type": "int",
            "label": "Min samples split",
            "min": 2,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.decision_tree.min_samples_split",
        },
        {
            "name": "min_samples_leaf",
            "type": "int",
            "label": "Min samples leaf",
            "min": 1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.decision_tree.min_samples_leaf",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.decision_tree.random_state",
        },
    ],
    "mlp": [
        {
            "name": "hidden_layer_sizes",
            "type": "int_list",
            "label": "Layers (neurons)",
            "placeholder": "e.g. 64,32,16",
            "help_key": "controls.regression.hyperparams.models.mlp.hidden_layer_sizes",
        },
        {
            "name": "activation",
            "type": "choice",
            "label": "Activation",
            "choices": ["relu", "tanh", "logistic", "identity"],
            "help_key": "controls.regression.hyperparams.models.mlp.activation",
        },
        {
            "name": "solver",
            "type": "choice",
            "label": "Solver",
            "choices": ["adam", "lbfgs", "sgd"],
            "help_key": "controls.regression.hyperparams.models.mlp.solver",
        },
        {
            "name": "alpha",
            "type": "float",
            "label": "Alpha",
            "min": 0.0,
            "max": 10.0,
            "step": 0.0001,
            "decimals": 4,
            "help_key": "controls.regression.hyperparams.models.mlp.alpha",
        },
        {
            "name": "learning_rate",
            "type": "choice",
            "label": "Learning rate",
            "choices": ["constant", "invscaling", "adaptive"],
            "help_key": "controls.regression.hyperparams.models.mlp.learning_rate",
        },
        {
            "name": "max_iter",
            "type": "int",
            "label": "Max iterations",
            "min": 50,
            "max": 5000,
            "step": 50,
            "help_key": "controls.regression.hyperparams.models.mlp.max_iter",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.models.mlp.random_state",
        },
    ],
}

REGRESSION_SELECTOR_PARAM_SPECS: dict[str, list[dict[str, object]]] = {
    "variance_threshold": [
        {
            "name": "threshold",
            "type": "float",
            "label": "Variance threshold",
            "min": 0.0,
            "max": 1.0,
            "step": 0.01,
            "decimals": 3,
            "help_key": "controls.regression.hyperparams.selectors.variance_threshold.threshold",
        },
    ],
    "select_k_best": [
        {
            "name": "k",
            "type": "int_all",
            "label": "Number of features",
            "min": -1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.select_k_best.k",
        },
    ],
    "mutual_info": [
        {
            "name": "k",
            "type": "int_all",
            "label": "Number of features",
            "min": -1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.mutual_info.k",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.mutual_info.random_state",
        },
    ],
    "random_forest_importance": [
        {
            "name": "threshold",
            "type": "text",
            "label": "Threshold (median, mean, or float)",
            "help_key": "controls.regression.hyperparams.selectors.random_forest_importance.threshold",
        },
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of trees",
            "min": 10,
            "max": 2000,
            "step": 10,
            "help_key": "controls.regression.hyperparams.selectors.random_forest_importance.n_estimators",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.random_forest_importance.random_state",
        },
    ],
    "extra_trees_importance": [
        {
            "name": "threshold",
            "type": "text",
            "label": "Threshold (median, mean, or float)",
            "help_key": "controls.regression.hyperparams.selectors.extra_trees_importance.threshold",
        },
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of trees",
            "min": 10,
            "max": 2000,
            "step": 10,
            "help_key": "controls.regression.hyperparams.selectors.extra_trees_importance.n_estimators",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.extra_trees_importance.random_state",
        },
    ],
    "gradient_boosting_importance": [
        {
            "name": "threshold",
            "type": "text",
            "label": "Threshold (median, mean, or float)",
            "help_key": "controls.regression.hyperparams.selectors.gradient_boosting_importance.threshold",
        },
        {
            "name": "n_estimators",
            "type": "int",
            "label": "Number of estimators",
            "min": 10,
            "max": 500,
            "step": 10,
            "help_key": "controls.regression.hyperparams.selectors.gradient_boosting_importance.n_estimators",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.gradient_boosting_importance.random_state",
        },
    ],
    "rfe_ridge": [
        {
            "name": "n_features_to_select",
            "type": "int_optional",
            "label": "Features to select",
            "min": 1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.rfe_ridge.n_features_to_select",
        },
        {
            "name": "step",
            "type": "int",
            "label": "Features to remove per step",
            "min": 1,
            "max": 10,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.rfe_ridge.step",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.selectors.rfe_ridge.random_state",
        },
    ],
}

REGRESSION_REDUCER_PARAM_SPECS: dict[str, list[dict[str, object]]] = {
    "pca": [
        {
            "name": "n_components",
            "type": "int_optional",
            "label": "Components",
            "min": 0,
            "max": 1000,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.pca.n_components",
        },
        {
            "name": "svd_solver",
            "type": "choice",
            "label": "SVD solver",
            "choices": ["auto", "full", "arpack", "randomized"],
            "help_key": "controls.regression.hyperparams.reducers.pca.svd_solver",
        },
        {
            "name": "whiten",
            "type": "bool",
            "label": "Whiten components",
            "help_key": "controls.regression.hyperparams.reducers.pca.whiten",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.pca.random_state",
        },
    ],
    "pls_regression": [
        {
            "name": "n_components",
            "type": "int",
            "label": "Components",
            "min": 1,
            "max": 1000,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.pls_regression.n_components",
        },
        {
            "name": "scale",
            "type": "bool",
            "label": "Scale data",
            "help_key": "controls.regression.hyperparams.reducers.pls_regression.scale",
        },
        {
            "name": "max_iter",
            "type": "int",
            "label": "Max iterations",
            "min": 50,
            "max": 5000,
            "step": 50,
            "help_key": "controls.regression.hyperparams.reducers.pls_regression.max_iter",
        },
        {
            "name": "tol",
            "type": "float",
            "label": "Tolerance",
            "min": 0.000001,
            "max": 1.0,
            "step": 0.0001,
            "decimals": 6,
            "help_key": "controls.regression.hyperparams.reducers.pls_regression.tol",
        },
    ],
    "fast_ica": [
        {
            "name": "n_components",
            "type": "int_optional",
            "label": "Components",
            "min": 0,
            "max": 1000,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.n_components",
        },
        {
            "name": "algorithm",
            "type": "choice",
            "label": "Algorithm",
            "choices": ["parallel", "deflation"],
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.algorithm",
        },
        {
            "name": "whiten",
            "type": "choice",
            "label": "Whiten mode",
            "choices": ["unit-variance", "arbitrary-variance"],
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.whiten",
        },
        {
            "name": "fun",
            "type": "choice",
            "label": "Contrast function",
            "choices": ["logcosh", "exp", "cube"],
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.fun",
        },
        {
            "name": "max_iter",
            "type": "int",
            "label": "Max iterations",
            "min": 50,
            "max": 5000,
            "step": 50,
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.max_iter",
        },
        {
            "name": "tol",
            "type": "float",
            "label": "Tolerance",
            "min": 0.000001,
            "max": 1.0,
            "step": 0.0001,
            "decimals": 6,
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.tol",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.fast_ica.random_state",
        },
    ],
    "factor_analysis": [
        {
            "name": "n_components",
            "type": "int_optional",
            "label": "Components",
            "min": 0,
            "max": 1000,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.factor_analysis.n_components",
        },
        {
            "name": "svd_method",
            "type": "choice",
            "label": "SVD method",
            "choices": ["randomized", "lapack"],
            "help_key": "controls.regression.hyperparams.reducers.factor_analysis.svd_method",
        },
        {
            "name": "iterated_power",
            "type": "int",
            "label": "Iterated power",
            "min": 1,
            "max": 20,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.factor_analysis.iterated_power",
        },
        {
            "name": "rotation",
            "type": "choice",
            "label": "Rotation",
            "choices": [None, "varimax", "quartimax"],
            "help_key": "controls.regression.hyperparams.reducers.factor_analysis.rotation",
        },
        {
            "name": "tol",
            "type": "float",
            "label": "Tolerance",
            "min": 0.000001,
            "max": 1.0,
            "step": 0.0001,
            "decimals": 6,
            "help_key": "controls.regression.hyperparams.reducers.factor_analysis.tol",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.factor_analysis.random_state",
        },
    ],
    "truncated_svd": [
        {
            "name": "n_components",
            "type": "int",
            "label": "Components",
            "min": 1,
            "max": 1000,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.truncated_svd.n_components",
        },
        {
            "name": "algorithm",
            "type": "choice",
            "label": "Algorithm",
            "choices": ["randomized", "arpack"],
            "help_key": "controls.regression.hyperparams.reducers.truncated_svd.algorithm",
        },
        {
            "name": "n_iter",
            "type": "int",
            "label": "Power iterations",
            "min": 1,
            "max": 50,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.truncated_svd.n_iter",
        },
        {
            "name": "tol",
            "type": "float",
            "label": "Tolerance",
            "min": 0.0,
            "max": 1.0,
            "step": 0.0001,
            "decimals": 6,
            "help_key": "controls.regression.hyperparams.reducers.truncated_svd.tol",
        },
        {
            "name": "random_state",
            "type": "int",
            "label": "Random state",
            "min": 0,
            "max": 9999,
            "step": 1,
            "help_key": "controls.regression.hyperparams.reducers.truncated_svd.random_state",
        },
    ],
}

REGRESSION_REDUCER_DEFAULTS: dict[str, dict[str, object]] = {
    "pca": {
        "n_components": None,
        "svd_solver": "auto",
        "whiten": False,
        "random_state": 0,
    },
    "pls_regression": {
        "n_components": 2,
        "scale": True,
        "max_iter": 500,
        "tol": 0.000001,
    },
    "fast_ica": {
        "n_components": None,
        "algorithm": "parallel",
        "whiten": "unit-variance",
        "fun": "logcosh",
        "max_iter": 200,
        "tol": 0.0001,
        "random_state": 0,
    },
    "factor_analysis": {
        "n_components": None,
        "svd_method": "randomized",
        "iterated_power": 3,
        "rotation": None,
        "tol": 0.01,
        "random_state": 0,
    },
    "truncated_svd": {
        "n_components": 2,
        "algorithm": "randomized",
        "n_iter": 5,
        "tol": 0.0,
        "random_state": 0,
    },
}

__all__ = [
    "REGRESSION_MODEL_PARAM_SPECS",
    "REGRESSION_SELECTOR_PARAM_SPECS",
    "REGRESSION_REDUCER_PARAM_SPECS",
    "REGRESSION_REDUCER_DEFAULTS",
]
